# Generated by Django 4.2.6 on 2023-11-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bairoo',
            new_name='bairro',
        ),
    ]
